# Generated by Django 5.0.7 on 2025-04-25 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nickname", models.CharField(max_length=100)),
                ("make", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
                ("year", models.CharField(max_length=4)),
                ("fuel_type", models.CharField(max_length=50)),
                ("drive", models.CharField(max_length=50)),
                ("transmission", models.CharField(max_length=50)),
                ("v_class", models.CharField(max_length=50)),
                ("disp", models.CharField(max_length=50)),
                ("city_km_per_gallon", models.FloatField()),
                ("highway_km_per_gallon", models.FloatField()),
                ("kg_per_gallon", models.FloatField()),
                ("icon_id", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("city_distance", models.FloatField()),
                ("highway_distance", models.FloatField()),
                ("total_distance", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Utility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bill_type", models.CharField(max_length=50)),
                ("bill_amount", models.FloatField()),
                ("total_emission", models.FloatField()),
                ("num_people", models.IntegerField()),
                ("emission_per_person", models.FloatField()),
                ("bill_start_date", models.DateField()),
                ("bill_end_date", models.DateField()),
                ("days", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="VehicleSpec",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.FloatField()),
                ("highway", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Journey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_emission", models.FloatField()),
                ("journey_date", models.DateField()),
                (
                    "trans_mode",
                    models.CharField(
                        choices=[
                            ("car", "Car"),
                            ("bus", "Bus"),
                            ("walk/bike", "Walk/Bike"),
                            ("skytrain", "Skytrain"),
                        ],
                        max_length=20,
                    ),
                ),
                ("route_save", models.BooleanField(default=False)),
                (
                    "car",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="carbontracker.car",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="carbontracker.route",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="car",
            name="car_spec",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="carbontracker.vehiclespec",
            ),
        ),
    ]
